// This file is automatically generated by vscode-react-native@0.2.4
// Please do not modify it manually. All changes will be lost.
try {
    var path = require("path");
    var Launcher = require("/Users/lintonye/.vscode/extensions/vsmobile.vscode-react-native-0.2.4/out/debugger/launcher.js").Launcher;
    new Launcher("/Users/lintonye/git-repos/react-native-diary/transitions", "/Users/lintonye/git-repos/react-native-diary/transitions").launch();
} catch (e) {
    throw new Error("Unable to launch application. Try deleting .vscode/launchReactNative.js and restarting vscode.");
}